let eid=101
let ename="rahul"
let avail=true
let loc;
let email=[bbvuvbregmail.com,]
let details={}
console.log(typeof eid)
console.log(typeof ename)
console.log(typeof avail)
console.log(typeof loc)
console.log(typeof email)
console.log(typeof details)